# Generated by Django 5.2.7 on 2025-12-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='prazo',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='prioridade',
        ),
    ]
